"""Reusable pieces for the event-based BB84 post-processing example."""

from .agents import AlicePostProcessor, BB84PostProcessor, BobPostProcessor
from .cascade import (
    CascadeBlock,
    CascadeController,
    CascadeOutstanding,
    CascadeParityRequest,
    CascadeState,
    _cascade_block_key,
    cascade_block_key,
)
from .helpers import (
    binary_entropy,
    choose_permutation,
    choose_sample_positions,
    demo_entropy_budget,
    h2,
    measured_bit,
    parity,
    random_bits,
    remove_positions,
    require_bases,
    require_binary_bits,
    require_measured_bits,
    require_optional_binary_bits,
    require_positions,
    shuffled_range,
    toeplitz_hash,
)
from .messages import decode_body, encode_body

__all__ = [
    "AlicePostProcessor",
    "BB84PostProcessor",
    "BobPostProcessor",
    "CascadeBlock",
    "CascadeController",
    "CascadeOutstanding",
    "CascadeParityRequest",
    "CascadeState",
    "_cascade_block_key",
    "binary_entropy",
    "cascade_block_key",
    "choose_permutation",
    "choose_sample_positions",
    "decode_body",
    "demo_entropy_budget",
    "encode_body",
    "h2",
    "measured_bit",
    "parity",
    "random_bits",
    "remove_positions",
    "require_bases",
    "require_binary_bits",
    "require_measured_bits",
    "require_optional_binary_bits",
    "require_positions",
    "shuffled_range",
    "toeplitz_hash",
]
